id: issues-03-needs-info
name: GitOps.PullRequestIssueManagement
description: Handles when an issue needs information
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: >-
          When an issue has been triaged with `#needs-info` in a comment:
          - Assign to author
          - Remove the `Needs: Triage 🔍` label
          - Label with `Needs: Information`
        if:
          - payloadType: Issue_Comment
          - isOpen
          - commentContains:
              pattern: '#needs-info'
          - or:
              - activitySenderHasPermission:
                  permission: Admin
              - activitySenderHasPermission:
                  permission: Write
        then:
          - addLabel:
              label: 'Needs: Information'
          - removeLabel:
              label: 'Needs: Triage 🔍'
          - assignTo:
              author: True
onFailure:
onSuccess:
