name: 'PowerShell Tests'

on:
  pull_request:
    paths:
      - 'src/powershell/**'
jobs:
  run_pester_tests:
    name: Pester
    runs-on: Windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        shell: pwsh
        run: ./.build/start.ps1 -Task Test.PowerShell.All
