name: 'GitVersion'

on: [push]
jobs: 
    git-version:
        runs-on: windows-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0  
        - name: Install-GitVersion
          uses: gittools/actions/gitversion/setup@v0
          with:
            versionSpec: '5.x'
        - name: Run GitVersion
          id: gitversion
          uses: gittools/actions/gitversion/execute@v0
          with:
            useConfigFile: true
            configFilePath: GitVersion.yml
        - name: Show GitVersion
          run: |
            Write-Output ${{ steps.gitversion.outputs }}